(function(g){var window=this;var Oya=function(a,b){var c=[];g.qi(b,function(a){try{var b=g.rD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.qD(b)&&c.push(a):c.push(a)},a);
return c},Pya=function(a,b){var c=Oya(a,b);
(0,g.G)(c,function(a){g.rD.prototype.remove.call(this,a)},a)},Qya=function(){var a=g.$G;
Pya(a,a.g.Vd(!0))},R7=function(a,b){g.R0.call(this,g.T("YTP_MDX_TITLE"),0,a,b);
this.T=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},Rya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Sya=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},S7=function(){var a=Rya();
a&&a(!1,"No cast extension found")},T7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},U7=function(a){if(a>=g.Dra.length)S7();
else{var b=g.Dra[a],c="chrome-extension://"+b+g.Ara;0<=g.m2.indexOf(b)?Sya(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,T7(c,S7)):U7(a+1)}):T7(c,function(){U7(a+1)})}},V7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},Tya=function(){if(g.Bra){var a=2,b=Rya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;T7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",S7,c)}},Uya=function(){if(V7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Tya();a({command:"cast.sender.init"});return}}if(!window.chrome||V7("Edge"))S7();else if(Tya(),V7("Android")&&V7("Chrome/")&&window.navigator.presentation){a="";var b=g.Lh();55<=b?a="55":50<=b&&(a="50");T7("//www.gstatic.com/eureka/clank"+a+g.Ara,S7)}else U7(0)},Vya=function(a){g.sG[a]&&(a=g.sG[a],(0,g.G)(a,function(a){g.qG[a]&&delete g.qG[a]}),a.length=0)},Wya=function(a){var b=g.pG();
if(b)if(b.clear(a),a)Vya(a);else for(var c in g.sG)Vya(c)},Xya=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Dg(a)||"";b&&(this.port=":"+b);this.domain=g.Cg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Xa(a,"10.0")&&(this.o=!1))},Yya=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},Zya=function(){var a=window.document.createElement("a");
g.Vc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ya(a)},$ya=function(a,b){var c=g.Ad("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Wc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},aza=function(){var a=Zya(),b=window.document.getElementById(a),c=b&&g.FF(b,"loaded");
c||b&&!c||(b=$ya(a,function(){g.FF(b,"loaded")||(g.EF(b,"loaded","true"),g.wG(a),g.HE(g.Ea(Wya,a),0))}))},bza=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.eL||a},W7=function(a){g.pH("cloudview",a)},X7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},Y7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},cza=function(a,b,c,d){var e=!1;
Y7()||(a=new g.qI(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.bH("yt-remote-cast-available",a);g.xG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){W7("onReceiverSelected: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a);g.xG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){W7("onReceiverResumed: "+a.friendlyName);
g.bH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){W7("onSessionChange: "+g.xH(a));
a||g.dH("yt-remote-cast-receiver");g.xG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
W7("cloudview.createSingleton_: "+e);return e},dza=function(a){W7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},eza=function(){W7("dispose");
var a=Y7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);dza(!1);g.uG(Z7);Z7.length=0},$7=function(){return!!g.cH("yt-remote-cast-installed")},fza=function(){var a=g.cH("yt-remote-cast-receiver");
return a?a.friendlyName:null},gza=function(){W7("clearCurrentReceiver");
g.dH("yt-remote-cast-receiver")},a8=function(a){g.pH("cloudview",a)},hza=function(){return $7()?Y7()?Y7().getCastSession():(a8("getCastSelector: Cast is not initialized."),null):(a8("getCastSelector: Cast API is not installed!"),null)},b8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},c8=function(){$7()?Y7()?b8()?(W7("Requesting cast selector."),Y7().requestSession()):(W7("Wait for cast API to be ready to request the session."),Z7.push(g.tG("yt-remote-cast2-api-ready",c8))):a8("requestCastSelector: Cast is not initialized."):
a8("requestCastSelector: Cast API is not installed!")},d8=function(a,b){b8()?Y7().setConnectedScreenStatus(a,b):a8("setConnectedScreenStatus called before ready.")},e8=function(a){W7("setCastInstalled_ "+a);
g.bH("yt-remote-cast-installed",a)},iza=function(a,b){Y7().init(a,b)},jza=function(a,b){e8(!0);
X7(!1);iza(a,function(a){a?(dza(!0),g.wG("yt-remote-cast2-api-ready")):(a8("Failed to initialize cast API."),e8(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),eza());b(a)})},kza=function(a,b,c,d,e,f,k){bza()?cza(b,e,f,k)&&(X7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?jza(a,c):(window.__onGCastApiAvailable=function(b,d){b?jza(a,c):(a8("Failed to load cast API: "+d),e8(!1),X7(!1),g.dH("yt-remote-cast-available"),g.dH("yt-remote-cast-receiver"),eza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):aza():Uya())):W7("Cannot initialize because not running Chrome")},g8=function(a,b){g.gG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.FB;this.A=this.o=null;this.I=(0,g.z)(this.aO,this);this.F=(0,g.z)(this.rl,this);this.G=(0,g.z)(this.ZN,this);this.J=(0,g.z)(this.nO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Cu,this),lza(this))):c=3;0!=c&&(b?this.Cu(c):g.HE((0,g.z)(function(){this.Cu(c)},this),0));
var d=hza();d&&f8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},h8=function(a){return new g.wI(a.B.getPlayerContextData())},lza=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Ea(this.rQ,a),this))},a)},mza=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},i8=function(a,b){50>a.C.Jc()&&g.HB(a.C,b)},k8=function(a,b,c){var d=h8(a);
g.yI(d,c);-1E3!=d.g&&(d.g=b);j8(a,d)},l8=function(a,b,c){a.B.sendMessage(b,c)},j8=function(a,b){mza(a);
a.B.setPlayerContextData(g.BI(b));lza(a)},f8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.rl(null));
a.A=b;a.A&&(m8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.rl(a.A.media[0]))},nza=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=h8(a);b.contentId!=d.videoId&&m8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.yI(d,a.o.getEstimatedTime());j8(a,d)}else m8("No cast media video. Ignoring state update.")},m8=function(a){g.pH("CP",a)},n8=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),l8(this,b,c))},a)},o8=function(a){g.CH.call(this,"ScreenServiceProxy");
this.dd=a;this.o=[];this.o.push(this.dd.$_s("screenChange",(0,g.z)(this.FT,this)));this.o.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.XP,this)))},p8=function(){return g.x("yt.mdx.remote.currentScreenId_")},q8=function(a){g.pH("remote",a)},r8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},s8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},oza=function(){var a=s8();
if(g.Wb(a)){a=g.IH();var b=g.cH("yt-remote-session-name")||"",c=g.cH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},pza=function(a){a?(g.bH("yt-remote-session-app",a.app),g.bH("yt-remote-session-name",a.name)):(g.dH("yt-remote-session-app"),g.dH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},t8=function(){return g.x("yt.mdx.remote.connection_")},u8=function(){var a=t8();
return!!a&&3!=a.getProxyState()},qza=function(){return g.x("yt.mdx.remote.connectData_")},w8=function(){if(!v8){var a=g.x("yt.mdx.remote.screenService_");
v8=a?new o8(a):null}return v8},x8=function(){var a=g.JH();
if(!a)return null;var b=w8().ee();return g.BH(b,a)},y8=function(){var a=p8();
if(!a)return null;var b=w8().ee();return g.BH(b,a)},rza=function(){var a=w8().dd.$_gos();
var b=y8();b&&t8()&&(g.AH(a,b)||a.push(b));return Yya(a)},sza=function(){var a=rza(),b=y8();
b||(b=x8());return g.eb(a,function(a){return b&&g.uH(b,a.key)?!0:!1})},z8=function(){var a=sza();
!a&&$7()&&fza()&&(a={key:"cast-selector-receiver",name:fza()});return a},tza=function(){var a=rza();
$7()&&g.cH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},uza=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},B8=function(a){var b=t8();
r8(null);a||uza("");g.ua("yt.mdx.remote.connection_",a,void 0);A8&&((0,g.G)(A8,function(b){b(a)}),A8.length=0);
b&&!a?g.xG("yt-remote-connection-change",!1):!b&&a&&g.xG("yt-remote-connection-change",!0)},D8=function(a,b){y8()&&y8();
uza(a.id);var c=new g.HI(C8,a,s8());c.connect(b,qza());c.subscribe("beforeDisconnect",function(a){g.xG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){t8()&&B8(null)});
B8(c)},vza=function(){var a=x8();
a?(q8("Resume connection to: "+g.xH(a)),D8(a,0)):(g.QH(),gza(),q8("Skipping connecting because no session screen found."))},E8=function(){b8()?Y7().stopSession():a8("stopSession called before API ready.");
var a=t8();a&&(a.disconnect(1),B8(null))},wza=function(a){q8("remote.onCastSessionChange_: "+g.xH(a));
if(a){var b=y8();b&&b.id==a.id?d8(b.id,"YouTube TV"):(b&&E8(),D8(a,1))}else t8()&&E8()},xza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ZD("MDX_CONFIG")||b;g.$G&&Qya();g.KH();C8||(C8=new Xya(b?b.loungeApiHost:void 0),g.SH()&&(C8.g="/api/loungedev"));A8||(A8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",A8,void 0));oza();var c=w8();if(!c){var d=new g.cI(C8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=w8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);kza(a,d,function(a){a?p8()&&d8(p8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.xG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),q8("Initializing: "+g.ug(b)),F8.push(g.tG("yt-remote-cast2-availability-change",function(){g.xG("yt-remote-receiver-availability-change")})),F8.push(g.tG("yt-remote-cast2-receiver-selected",function(){r8(null);
g.xG("yt-remote-auto-connect","cast-selector-receiver")})),F8.push(g.tG("yt-remote-cast2-receiver-resumed",function(){g.xG("yt-remote-receiver-resumed","cast-selector-receiver")})),F8.push(g.tG("yt-remote-cast2-session-change",wza)),F8.push(g.tG("yt-remote-connection-change",function(a){a?d8(p8(),"YouTube TV"):x8()||(d8(null,null),gza())})),a=s8(),b.isAuto&&(a.id+="#dial"),g.mF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),q8(" -- with channel params: "+
g.ug(a)),pza(a),c.start(),p8()||vza())},G8=function(a,b,c){g.L.call(this);
this.F=a;this.T=b;this.o=new g.dG(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.qP);this.o.P(b,"captionschanged",this.YN);this.o.P(b,"captionssettingschanged",this.CC);this.o.P(b,"videoplayerreset",this.zo);this.o.P(b,"mdxautoplaycancel",this.GG);this.N=this.o.P(b,"onVolumeChange",this.TA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.gB,this);c.subscribe("remotePlayerChange",this.tl,this);c.subscribe("remoteQueueChange",this.zo,this);c.subscribe("autoplayUpNext",this.GA,
this);c.subscribe("previousNextChange",this.dB,this);c.subscribe("nowAutoplaying",this.VA,this);c.subscribe("autoplayDismissed",this.FA,this);this.suggestion=null;this.G=new g.IQ(64);this.A=new g.tt(this.xC,500,this);g.M(this,this.A);this.B=new g.tt(this.yC,1E3,this);g.M(this,this.B);this.C={};this.J=new g.tt(this.aD,1E3,this);g.M(this,this.J);this.I=new g.kk(this.NK,1E3,this);g.M(this,this.I);this.L=g.y;this.CC();this.zo();this.tl()},H8=function(a,b){var c=a.F,d=a.T.ga().lengthSeconds;
c.I=b||0;c.g.V("progresssync",b,d)},yza=function(a){H8(a,0);
a.A.stop();I8(a,new g.IQ(64))},f9=function(a,b){if(U8(a)&&!a.D){var c=null;
b&&(c={style:a.T.pi()},g.cc(c,b));a.g.qC(a.T.ga().videoId,c);a.C=h8(a.g).o}},g9=function(a,b){var c=a.T.Pf();
if(c){var d=c.ae();var e=c.listId.toString()}c=a.g;var f=a.T.ga().videoId,k=d;d=a.T.ga().playerParams;var l=h8(c),m=e||l.listId;k=k||0;var n={videoId:f,currentIndex:k};g.AI(l,f,k);g.t(b)&&(g.yI(l,b),n.currentTime=b);g.t(m)&&(n.listId=m);null!=d&&(n.playerParams=d);l8(c,"setPlaylist",n);e||j8(c,l);I8(a,new g.IQ(1))},zza=function(a,b){if(b){var c=a.T.wc("captions","tracklist",{ry:1});
c&&c.length?(a.T.Ed("captions","track",b),a.D=!1):(a.T.fl("captions"),a.D=!0)}else a.T.Ed("captions","track",{})},U8=function(a){return h8(a.g).videoId==a.T.ga().videoId},I8=function(a,b){a.B.stop();
var c=a.G;if(!g.NQ(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.T;g.J1(e.app,d,e.playerType)}a.G=b;Aza(a.F,c,b)}},o9=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.dE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.vX(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);Bza(this,g.tW(a))},Bza=function(a,b){if(3==a.A.Wa()){var c={RECEIVER_NAME:a.A.wc("remote","currentReceiver").name};
c=g.W(b,128)?g.T("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.W(b,4)?g.T("YTP_MDX_STATUS_PLAYING_2",c):g.T("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},r9=function(a){g.nX.call(this,a);
this.A={key:g.zH(),name:g.T("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.IQ(64);this.I=0;var b=g.mW(a).G;b&&(b=b.A&&b.A.g)&&(b=new R7(a,b),g.M(this,b));b=new o9(a);g.M(this,b);g.MW(a,b.element,4)},Aza=function(a,b,c){a.F=c;
a.g.V("presentingplayerstatechange",new g.SQ(c,b))},s9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)E8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Pf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.hc(l).videoId}else k=[e];f=a.g.getCurrentTime();c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,index:Math.max(a.g.zz(),0),currentTime:0==f?void 0:f}}else c=null;q8("Connecting to: "+g.ug(b));"cast-selector-receiver"==b.key?(r8(c||null),b8()?Y7().setLaunchParams(c||null):a8("setLaunchParams called before ready.")):!c&&u8()&&p8()==b.key?g.xG("yt-remote-connection-change",
!0):(E8(),r8(c||null),c=w8().ee(),(c=g.BH(c,b.key))&&D8(c,1))}};
g.p(R7,g.R0);R7.prototype.I=function(){var a=this.T.wc("remote","receivers");a&&1<a.length&&!this.T.wc("remote","quickCast")?(this.F=g.Fb(a,this.B,this),g.S0(this,(0,g.J)(a,this.B)),a=this.T.wc("remote","currentReceiver"),this.kf(this.B(a)),this.enable(!0)):this.enable(!1)};
R7.prototype.B=function(a){return a.key};
R7.prototype.jf=function(a){return"cast-selector-receiver"==a?g.T("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
R7.prototype.sd=function(a){g.R0.prototype.sd.call(this,a);this.T.Ed("remote","currentReceiver",this.F[a]);this.A.Mb()};
g.h=Xya.prototype;g.h.Zh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Mg(b+a,{})};
g.h.Au=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Ub:g.Ea(this.AT,c,!0),onError:g.Ea(this.zT,d),Gd:g.Ea(this.BT,d)};b&&(c.Nb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.XE(a,c)};
g.h.AT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.zT=function(a,b){a(Error("Request error: "+b.status))};
g.h.BT=function(a){a(Error("request timed out"))};
var Z7=[];g.A(g8,g.gG);g.h=g8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,n8(this,"play")):l8(this,"play"),k8(this,1,g.zI(h8(this))),this.V("remotePlayerChange")):i8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,n8(this,"pause")):l8(this,"pause"),k8(this,2,g.zI(h8(this))),this.V("remotePlayerChange")):i8(this,this.pause)};
g.h.lD=function(a){if(1==this.g){if(this.o){var b=h8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,n8(this,"seekTo",{newTime:a}))}else l8(this,"seekTo",{newTime:a});k8(this,3,a);this.V("remotePlayerChange")}else i8(this,g.Ea(this.lD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,n8(this,"stopVideo")):l8(this,"stopVideo");var a=h8(this);a.index=-1;a.videoId="";g.xI(a);j8(this,a);this.V("remotePlayerChange")}else i8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=h8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){m8("set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){m8("set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);l8(this,"setVolume",e)}c.muted=b;c.volume=a;j8(this,c)}else i8(this,g.Ea(this.setVolume,a,b))};
g.h.qC=function(a,b){if(1==this.g){var c=h8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ug(b.style),g.cc(d,c.o));l8(this,"setSubtitlesTrack",d);j8(this,c)}else i8(this,g.Ea(this.qC,a,b))};
g.h.Bu=function(a,b){if(1==this.g){l8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Rc.id});var c=h8(this);c.audioTrackId=b.Rc.id;j8(this,c)}else i8(this,g.Ea(this.Bu,a,b))};
g.h.kD=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);g.AI(c,a,b);j8(this,c)}l8(this,"previous")}else i8(this,g.Ea(this.kD,a,b))};
g.h.jD=function(a,b){if(1==this.g){if(a&&b){var c=h8(this);g.AI(c,a,b);j8(this,c)}l8(this,"next")}else i8(this,g.Ea(this.jD,a,b))};
g.h.Iw=function(){1==this.g?l8(this,"dismissAutoplay"):i8(this,this.Iw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.V("proxyStateChange",a,this.g)}g8.Z.dispose.call(this)};
g.h.X=function(){mza(this);this.B=null;this.C.clear();f8(this,null);g8.Z.X.call(this)};
g.h.Cu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.IB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.rQ=function(a,b){this.V(a,b)};
g.h.aO=function(a){if(!a)this.rl(null),f8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=h8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)m8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,j8(this,b)}};
g.h.rl=function(a){m8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),nza(this),this.V("remotePlayerChange")};
g.h.ZN=function(a){a?(nza(this),this.V("remotePlayerChange")):this.rl(null)};
g.h.nO=function(){var a=hza();a&&f8(this,a)};
g.h.ac=function(a){g.pH("CP",a)};
g.A(o8,g.CH);g.h=o8.prototype;g.h.ee=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.zp=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.ip=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.dd.$_ubk(this.o[a]);this.o.length=0;this.dd=null;o8.Z.X.call(this)};
g.h.FT=function(){this.V("screenChange")};
g.h.XP=function(){this.V("onlineScreenChange")};
var C8=null,A8=null,F8=[],v8=null;g.p(G8,g.L);g.h=G8.prototype;g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.L();this.g.unsubscribe("proxyStateChange",this.gB,this);this.g.unsubscribe("remotePlayerChange",this.tl,this);this.g.unsubscribe("remoteQueueChange",this.zo,this);this.g.unsubscribe("autoplayUpNext",this.GA,this);this.g.unsubscribe("previousNextChange",this.dB,this);this.g.unsubscribe("nowAutoplaying",this.VA,this);this.g.unsubscribe("autoplayDismissed",this.FA,this);this.g=this.F=null};
g.h.oz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(U8(this)){if(1081!=h8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":h8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.gj(c[0],c[1]);break;case "control_subtitles_set_track":f9(this,c[0]);break;case "control_set_audio_track":c=c[0],U8(this)&&this.g.Bu(this.T.ga().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();g9(this,0==c?void 0:c);break;case "control_seek":g9(this,c[0]);break;case "control_subtitles_set_track":f9(this,c[0]);break;case "control_set_audio_track":c=c[0],U8(this)&&this.g.Bu(this.T.ga().videoId,c)}};
g.h.YN=function(a){this.oz("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.CC=function(){var a=this.T.wc("captions","track");g.Wb(a)||f9(this,a)};
g.h.TA=function(a){if(U8(this)){this.g.unsubscribe("remotePlayerChange",this.tl,this);var b=Math.round(a.volume);a=!!a.muted;var c=h8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.J.start();this.g.subscribe("remotePlayerChange",this.tl,this)}};
g.h.qP=function(){g.Wb(this.C)||zza(this,this.C);this.D=!1};
g.h.gB=function(a,b){this.B.stop();2==b&&this.yC()};
g.h.tl=function(){if(U8(this)){this.A.stop();var a=h8(this.g);switch(a.g){case 1081:I8(this,new g.IQ(8));break;case 1:this.xC();I8(this,new g.IQ(8));break;case 1083:case 3:I8(this,new g.IQ(9));break;case 0:I8(this,new g.IQ(2));this.I.stop();H8(this,this.T.ga().lengthSeconds);break;case 1082:I8(this,new g.IQ(4));break;case 2:I8(this,new g.IQ(4));H8(this,g.zI(a));break;case -1:I8(this,new g.IQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.T("YTP_MDX_PLAYER_ERROR")},I8(this,new g.IQ(128,
a))}a=h8(this.g).o;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,zza(this,a));a=h8(this.g);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.J.isActive()||this.aD()}else yza(this)};
g.h.dB=function(){this.T.V("mdxpreviousnextchange")};
g.h.zo=function(){U8(this)||yza(this)};
g.h.GG=function(){this.g.Iw()};
g.h.GA=function(a){a&&(a=g.XE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Ub:(0,g.z)(this.rR,this)}))&&(this.L=(0,g.z)(a.abort,a))};
g.h.rR=function(a,b){var c=new g.KP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.VA=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.FA=function(){this.T.V("mdxautoplaycanceled")};
g.h.NK=function(a,b){-1==h8(this.g).g?g9(this,a):b&&this.g.lD(a)};
g.h.aD=function(){if(U8(this)){var a=h8(this.g);this.o.Ba(this.N);a.muted?this.T.mute():this.T.Qf();this.T.setVolume(a.volume);this.N=this.o.P(this.T,"onVolumeChange",this.TA)}};
g.h.xC=function(){this.A.stop();if(!this.g.ka()){var a=h8(this.g);a.kb()&&I8(this,new g.IQ(8));H8(this,g.zI(a));this.A.start()}};
g.h.yC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(o9,g.Y);o9.prototype.B=function(a){Bza(this,a.state)};g.p(r9,g.nX);g.h=r9.prototype;g.h.create=function(){xza(g.MN(g.X(this.g)));this.D.push(g.tG("yt-remote-before-disconnect",this.UN,this));this.D.push(g.tG("yt-remote-connection-change",this.AQ,this));this.D.push(g.tG("yt-remote-receiver-availability-change",this.eB,this));this.D.push(g.tG("yt-remote-auto-connect",this.yQ,this));this.D.push(g.tG("yt-remote-receiver-resumed",this.xQ,this));this.eB()};
g.h.load=function(){this.g.oq();g.nX.prototype.load.call(this);this.C=new G8(this,this.g,this.o);var a=qza();a=a?a.currentTime:0;var b=u8()?new g8(t8(),void 0):null;0==a&&b&&(a=g.zI(h8(b)));0!=a&&(this.I=a||0,this.g.V("progresssync",a,void 0));Aza(this,this.F,this.F);g.N1(this.g.app,6)};
g.h.unload=function(){this.g.V("mdxautoplaycanceled");this.B=this.A;g.Ye(this.C,this.o);this.o=this.C=null;g.nX.prototype.unload.call(this);g.N1(this.g.app,5)};
g.h.X=function(){g.uG(this.D);g.nX.prototype.X.call(this)};
g.h.Xk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.oz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.tH=function(){return this.loaded?this.C.suggestion:null};
g.h.Ff=function(){return this.o?h8(this.o).Ff:!1};
g.h.hasNext=function(){return this.o?h8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.qK=function(){var a=h8(this.o),b=this.g.ga();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.F)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.F)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.F?a.B+((0,g.F)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.F)()-a.A)/1E3:a.D}};
g.h.rK=function(){this.o&&this.o.jD()};
g.h.sK=function(){this.o&&this.o.kD()};
g.h.UN=function(a){1==a&&(this.J=this.o?h8(this.o):null)};
g.h.AQ=function(){var a=u8()?new g8(t8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Xe(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.xz(a.videoId,g.zI(a)));this.g.V("videodatachange","newdata",this.g.ga(),3)};
g.h.eB=function(){this.G=[this.A].concat(tza());var a=z8()||this.A;s9(this,a);this.g.va("onMdxReceiversChange")};
g.h.yQ=function(){var a=z8();s9(this,a)};
g.h.xQ=function(){this.B=z8()};
g.h.pK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?c8():s9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&c8(),!0):!1}};
g.h.tK=function(){l8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ud=function(){return!1};g.WZ.remote=r9;})(_yt_player);
